# Generated by Django 5.1.4 on 2024-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('remuneracao', models.IntegerField()),
            ],
        ),
    ]
